### ISSUE TITLE
summary page updates

### ISSUE THREAD

**Issue by jpata** [jpata/cms-reco-profiling-web#4]
Thanks @xoqhdgh1002 for the nice [update](https://indico.cern.ch/event/1023745/#3-progress-report) today! Here's some points from my side:

1. please open a PR in this repository with the updates to the HTML summary page, we can comment on the PR more easily

2. we have pre-generated the profiling inputs for all relevant releases in `/eos/cms/store/user/cmsbuild/profiling/data`, over time, we will likely want to update the webpage to have all the plots derived from these inputs 

3. I have pre-generated SQL files in EOS in the common web space, which you can use in the HTML summary page. However, in the longer term (e.g. for pre6 in 2 weeks), I think it would be good if you can generate those files yourself and put them in the same location, following the existing path structure.
I propose this pattern:
```bash
$ ls /eos/project/c/cmsweb/www/reco-prof/cgi-bin/data/releases/CMSSW_11_3_0_pre5/23434.21/step3
cpu_endjob.sql3  mem_live.1.sql3  mem_live.50.sql3  mem_live.99.sql3
```

4. you should also put all the other intermediate files linked from the HTML (e.g. compare_cpu, compare_mem) in the common web space in predictable places, e.g. `/eos/project/c/cmsweb/www/reco-prof/data/releases/CMSSW_11_3_0_pre5/23434.21/step3`.

5. for circles, you don't need to copy the JSON, you can use this link: http://cms-reco-profiling.web.cern.ch/cms-reco-profiling/circles/piechart.php?colours=default&groups=reco_PhaseII&threshold=0, which is always automatically up to date with the results from the bot. You can generate the correct URL for the summary page on the fly using string substitution and making the appropriate changes

Let me know if you have any questions. @slava77 feel free to add/correct.

**Comment by slava77** [comment]
>     2\. you can use this link: http://cms-reco-profiling.web.cern.ch/cms-reco-profiling/circles/piechart.php?colours=default&groups=hlt&threshold=0

please make sure to select a correct group name. `hlt` is not appropriate in our case

**Comment by xoqhdgh1002** [comment]
Thank you so much for the comments!
Lately, I couldn't check the email and comments. Because I'm writing the thesis. Sorry for my late reply
I will change the web page and send a reply to you
________________________________________
보낸 사람: Joosep Pata ***@***.***
보낸 날짜: 2021년 3월 31일 수요일 오후 11:27
받는 사람: jpata/cms-reco-profiling-web
참조: Bongho Tae; Mention
제목: [jpata/cms-reco-profiling-web] summary page updates (#4)

Thanks @xoqhdgh1002<https://github.com/xoqhdgh1002> for the nice update<https://indico.cern.ch/event/1023745/#3-progress-report> today! Here's some points from my side:

  1.  please open a PR in this repository with the updates to the HTML summary page, we can comment on the PR more easily

  2.  we have pre-generated the profiling inputs for all relevant releases in /eos/cms/store/user/cmsbuild/profiling/data, over time, we will likely want to update the webpage to have all the plots derived from these inputs

  3.  I have pre-generated SQL files in EOS in the common web space, which you can use in the HTML summary page. However, in the longer term (e.g. for pre6 in 2 weeks), I think it would be good if you can generate those files yourself and put them in the same location, following the existing path structure.
I propose this pattern:

$ ls /eos/project/c/cmsweb/www/reco-prof/cgi-bin/data/releases/CMSSW_11_3_0_pre5/23434.21/step3
cpu_endjob.sql3  mem_live.1.sql3  mem_live.50.sql3  mem_live.99.sql3

  1.  you should also put all the other intermediate files linked from the HTML (e.g. compare_cpu, compare_mem) in the common web space in predictable places, e.g. /eos/project/c/cmsweb/www/reco-prof/data/releases/CMSSW_11_3_0_pre5/23434.21/step3.

  2.  for circles, you don't need to copy the JSON, you can use this link: http://cms-reco-profiling.web.cern.ch/cms-reco-profiling/circles/piechart.php?colours=default&groups=hlt&threshold=0, which is always automatically up to date with the results from the bot. You can generate the correct URL for the summary page on the fly using string substitution

Let me know if you have any questions. @slava77<https://github.com/slava77> feel free to add/correct.

**Comment by xoqhdgh1002** [comment]
In pre5 profiling data, the sql3 file about CPU doesn't have the process include `doEvent`. I look forward to your comments.

**Comment by jpata** [comment]
> In pre5 profiling data, the sql3 file about CPU doesn't have the process include `doEvent`. I look forward to your comments.

igprof pp outputs are broken in pre5, the issue is being addressed by the core team: 
https://github.com/cms-sw/cmssw/issues/33297

For the moment, you can skip igprof pp in pre5.

**Comment by jpata** [comment]
The update with pre4 and pre5 was merged in https://github.com/jpata/cms-reco-profiling-web/pull/8.
A follow-up comment has been posted at #9, meanwhile we can close this issue.
